%% gps_to_rawdata:
function [rawdata] = get_data(msg_mot)
	rawdata = struct();
    rawdata.latitude = rad2deg(msg_mot.Latitude);	% radians
    rawdata.longitude = rad2deg(msg_mot.Longitude);	% radians
    rawdata.el = msg_mot.Altitude;					% m
    rawdata.Yaw = msg_mot.Heading - pi/2;			% rad
    rawdata.YawRate = msg_mot.RotationRate(3);		% rad/s
    rawdata.Vx = msg_mot.Velocity(1);				% m/s
    rawdata.Vy = msg_mot.Velocity(2);				% m/s
    rawdata.x_gps_cg = 0.99; 						% m
    rawdata.y_gps_cg = 0;							% m
    rawdata.steer_L1 = NaN;
    rawdata.steer_R1 = NaN;
    rawdata.Alpha_L1 = NaN;
    rawdata.Alpha_R1 = NaN;
    rawdata.Fy_L1 = NaN;
    rawdata.Fy_R1 = NaN;
    rawdata.Fz_L1 = NaN;
    rawdata.Fz_R1 = NaN;
    rawdata.Fx  = NaN;
    rawdata.Gear_CL = NaN;
    rawdata.RGear_Tr = NaN;
    rawdata.AV_Eng = NaN;     					% rpm
    rawdata.Throttle = NaN;						% [0, 1]
    rawdata.Throttle_Eng = NaN;			
    rawdata.M_EngOut = NaN;
    rawdata.AVy_L1 = NaN;							% rpm
    rawdata.AVy_L2 = NaN;
    rawdata.AVy_R1 = NaN;
    rawdata.AVy_R2 = NaN;
    rawdata.My_Dr_L1 = NaN;
    rawdata.My_Dr_L2 = NaN;
    rawdata.My_Dr_R1 = NaN;
    rawdata.My_Dr_R2 = NaN;
    rawdata.F_pedal = NaN;
    rawdata.Bk_pedal = NaN;
end